// Copyright (C) 2020,2024-2025 azumakuniyuki and sisimai development team, All rights reserved.
// This software is distributed under The BSD 2-Clause License.
//  ____  _____ ____ ____ _________  ____  
// |  _ \|  ___/ ___| ___|___ /___ \|___ \ 
// | |_) | |_ | |   |___ \ |_ \ __) | __) |
// |  _ <|  _|| |___ ___) |__) / __/ / __/ 
// |_| \_\_|   \____|____/____/_____|_____|

// Package "rfc5322" provides functions for email addresses, Date: header, Received: headers, and
// other headers and messages related to RFC5322. https://datatracker.ietf.org/doc/html/rfc5322
package rfc5322

// The part of "Received:" headers generated by qmail or qmail-clone
//   - Received: (qmail 2202 invoked from network); 15 Oct 2015 06:22:22 -0000
//   - Received: (qmail 2220 invoked by uid 2); 17 Jul 2014 08:30:40 -0000
// Do not exclude the following strings:
//   - Received: (qmail 2204 invoked for bounce); 29 Apr 2010 00:00:00 -000
var woReceived = []string{" invoked by uid", " invoked from network"}

